#### OBJECT: Upon the all-new Regolamento Macchine
#### DATE: march 7th 2023
#### AUTHOR: mathon
---
---

- foreseen issue on next mey/june 2023
- regolamento è applicabile direttamente a tutti gli stati membri senza che ve
ne sia la necessità che lo stato membro lo recepisca con legge interna, quindi
non v'è variazione da stato a stato > c'è un vincolo di stato ma non di mezzi
> la direttiva lascia infatti margini e spazi di manovra, il regolamento NO!
as esempio cosa fare con i macchinari antecedenti non se ne fa menzione nella
vecchia 2006/42/CE mentre c'è in quella non comunitaria nazionale!

> il regolamento è certo!
ed entra in vigore e verrà applicato esattamente nello stesso momento in tutti
gli stati membri - la direttiva invece doveva essere recepita, ed ogni stato lo
faceva coi propri tempi legislativi, in italia è stata recepita ed applicata nel
2010, con due mesi di ritardo!

> nella prima direttiva la vacanza legislativa italiana è stata di quasi 2 anni!
> ovvero stato di indeterminazione legislativo all'interno del quale non v'è
una regola > tutte queste cose col regolamento cesseranno di esistere

> la tendenza è che tutte le direttive insieme ad altre normative di prodottto diverranno regolamenti

> la direttiva serve affinché il mercato unico funzioni in EU, diversamente i
produttori locali sarebbero avantaggiati

> gli stati membri hanno il divieto di modificare o normare le normative di
prodotto, altrimenti altererebbero il mercato locale: le regole nazionali non
possono in nessun modo gravare sui fabbricanti ma solo sull'utilizzatore, quello
sì! (Art.15)

> serve a regolamentare il mercato unico, con regole comuni a tutti gli stati
membri i), e ii) a garantire la sicurezza e la salute dei cittadini comunitari
>> leggi che si applicano a tutti gli stati europei + ai paesi dello spazio
europeo (zona verde) + SWISS + paesi che hanno accordi con l'EU tipo San Marino,
Turchia, e Lichteistein che applica il trattato pur non essendo paesi membri

>> si veda il **testo consolidato** per chiarimenti sulla 2006/42/CE

> nella direttiva macchine non ci sono res che regolamentino sui requisiti
ambientali, a meno per le macchine che hanno a che fare con i pesticidi

> accordo provvisori del 7/2-2023

> il nuovo NLF nuovo quadro legislativo, è la cornice di rif nella quale
andranno a confluire tutte le normative da oggi in avanti

> la EMI ad esempio è già una direttiva del nuovo quadro legislativo
quindi la dichiarazione di conformità non soffrirà questo problema di far
quadrare dure direttive che puntavano a quadri di riferimento legislativi
differernti

> dal nostro punto di vista il nuovo NFL è l'istituzione dei moduli A, B, C, ..
H, ovvero l'istituzione dei moduli - che oggi non c'è.
c'è un nuovo approccio: io ti dico cosa devi fare coi res, poi ci son le norme
tecniche, vedi tu come fare! se con o senza.

questo approccio non è cambiato, ma nel nuovo quadro legislativo sono stati
introdottti due nuovi attori economici, che sono 4: il fabbricante,
il mandatario (che è cambiato), l'importatore, e <missis>

> partiamo dai considerando! nei quali si usa sempre il condizionale
> i requisiti di carattere ambientale sono ancora solamente per i macchinari di
pesticidi, però si tiene in considerazione la salvagurdia della sicurezza e
saluta degli animali domestici ed ambientali

> si valuta anche cosa fare coi macchinari importati esterno anche se di seconda
mano

> fondamentale è che si affrontano gli aspetti relativi alle nuove tecnologie,
ovvere aspetti digitali e macchine che sono in gradi di apprendere nuove
istruzioni, ovvero che potrebbero essere dotate di AI

> uscirà cmq un regolamento sull'AI dedicato
> si applicherà una marcatura CE per la prima volta ad un bene immateriale,
ovvero al SW - anche se in reatà è già previsto per i dispositivi medici

> ad oggi non vi è la necessità di marcare CE un componente SW poiché la
2006/42/CE non dice nulla sui componenti digitali - il SW è un dicui dell'HW

> si precisa che non tutti i res si applicano alle quasi-macchine, cosa scontata
ovvio, ma nulla di più in tal senso (cioè è stato fatto poco)

> si parla di atti esplicitamente malevoli, ovvero si fa riferimento ad attacchi
hacker, ovvero di atto criminale

> definizione di modifica sostanziale, ovvero il nuovo RM si applicherà non solo
alle macchine nuove ma anche a tutte quelle modifiche che non sono espressamente
previste dal fabbricante!

> si specifica però che le operazioni di manutenzione non sono modifica
sostanziale, però chi la applica, detta mofica sostanziale, dovrà riemettere la
dichiarazione di conformità rispettando tutti i requisiti del RM

> si distingue tra la immissione sul mercato e la messa in servivio
> importatori: nuova figura
> distributori: altro nuovo attore economico introdotto

> gli operatori economici, compreso il distributore, è responsabile per la
documentazione della macchina

> la documentazione potrà inoltre essere fornita d'ora in avanti in formato
digitale!

> la commissione ha introdotto la possibilità di varare delle norme comuni
quando le norme tecniche non soddisfano i res previsti

> i risultati delle norme tecniche hanno valore legislativo!
> avere delle **specifiche tecniche** che sono emanate dalla commmissione fa
saltare il banco! ovvero i modi coi quali rispettare il regolamento che vengono
imposti dall'altro, ovvero dalla commissione!

> la discussione verteva proprio sul compromesso di fare una specifica comune
solamente quando una norma non c'è, oppure gli enti normativi non l'hanno
valutata in tempi ragionevoli, allora io commissione me la faccio da sola!

le norme dovrebbero essere scritte dalle persone che lavorano sulle macchine e
per soddisfare le leggi di mercato (la macchina non può essere troppo costosa)
per questo il rischio è questo se le specifiche teniche (quand'anche comune) con
la stessa valenze delle norme armonizzate siano troppo astratte e difficili da
rispettare - infatti si è imposto che, in presenza di entrambre, le specifiche
tecniche comuni devono cadere a favore della norma armonizzata

la commissione deve comuque coinvolgere le parti interessate nel processo di
stesura della specifica tecnica comune

il concetto è che la commissione dovrebbere solamente scrivere i res e cioè le
norme da rispettare

> la dichiarazione di conformità diventerà UE e non sarà più CE!

> la prima cosa che qualifica una macchina è che vi devono essere organi
meccanici (elemnti) in movimento

> comunque se c'è il circuito di comando è una macchina: discussione su EVs, che
sono dei componenti nel caso di EV pneumatico

> quando una macchina è propriamente detta e quando è una quasi macchina?
> se vi è una **applicazione ben determinata** ovvero una applicazione non
ipotetica, ma per la quale è stata progettata dal fabbricante e mesa in
commercio - l'uso deve essere quello previsto (in modo chiaro ed esaustivo) dal
fabbricante, e questo ancor prima di redigere la analisi di valutazione dei
rischi.

> la destinazione d'uso va scritta in forma succinta ma in modo molto
dettagliato nel manuale d'uso e di installazione della macchina

> esempio indicare il grado massimo di utilizzo del prodotto!
se non lo scrivo come fa l'utilizzatore a saperlo!

> macchine che cessano la propria azione non appena la forza di applicazione
umana o animale cessano di esistere non sono macchine!

la definizione di macchina non è cambiata a parte per la parte f): si fa
menzione del softwrae destinato alla specifca applicazion prevista dal
fabbricante, ovvero anche il SW deve essere espressamente previsto per la
applicazione espressamente prevista dal fabbricante (si configura una maggiore
chiarezza)

cioè: se la macchina fa qualcosa di differente da ciò che è previsto dall'
analisi di valutazione dei rischi, la macchina non è conforme!

il SW non deve influenzare la valutazione dei rischi, il SW di sicurezza la
altera quello (SW) applicativo no!

i parametri SW che alterano la sicurezza della macchina non devono essere
alterati o alterabili!

solo il SW che comprende la sicurezza che necessità di marcatura CE

> definizione dei componenti di sicurezza

> nel manuale di istruzioni bisogna specificare se parte delle protezioni sono
svolte da elementi ambientali (ad esempio un muro) e poi specificare anche cosa
fare nel caso in cui si dovesse spostare l'installazione del macchinario (si
veda la **quida all'applicazione della direttiva macchine**)

> nella nuova defizione di componente di sicurezza si specifica, rispetto al
passato, che è stato aggiunto un componente di natura fisica o digitale, e
quindi con una componente SW che svolge cioè funzioni di natura safe!

se tale SW lo scrive non il fabbricante ma un soggetto terzo e lo immetti sul
mercato, lo deve marcare CE!

il SW di sicurezza lo scrivo sulla base di una specifica di sicurezza che è
basata sulla valutazione dei rischi, che fa il fabbricante!
ecco perché se lo fa un soggetto terzo e vi è l'immisione sul mercato allora il
soggetto terzo deve marcare CE il SW (questo è elemento di novità)

>> quando faccio la analisi di valutazione dei rischi sto scrivendo una
specifica SW su quelle che sono le funzioni di sicurezza, e quindi scrivo cosa
mi aspetto che il SW safe esegua / faccia!

> affidabilità dei circuiti di comando: SIL e PL
> nel fare la stima di questo valore di affidabiltà il SW non rientrà, perché
non ha errori causali etc etc, però si richiede che nello scrivere il SW si
siano rispettati tutti <missis> che mi consentono, secondo la specifica tecnica
di sicurezza, mi consentono di avere una macchina sicura (secondo questa
definizione)
> anche con un PLC di sicurezza una macchina con affidabilità di 1e10-9 può
comunque guastarsi

>> il SW safe ora va validato e marcato

> il fabbricante si accerterà che il SW di sicurezza è (a sua volta) marcato CE
che comprende anche aspetti HW - per poter redigere la dichiarazione di
conformità

res 1.2.1

res 1.1.2 (sulle interfacce)
res 1.1.6 (sull'ergonomia)


il PL si calcola solo sulla parte HW, non sulla parte SW: il software ha aspetti
deterministici, cioè non può avere guasti (ma errori, quelli si)

>> **bisognerebbe identificare il SW con un ID univoco per intercettare
manomissioni!**


>> bisognerebbe avere il CRC del SW di tutte le macchine installate!
annotato dove però?

>> robot è quasi macchina se manca l'end-effector
>> perché ha bisogno di altri oggetti per svolgere la propria funzione, ovvero
hanno bisogno di altri elementi per poter a termine la propria azione /
applicazione per la quale sono stati progettati dal fabbricante

> i robot collaborativi sono instrinsecamente sicuri

> una macchina che non rispetta tutti i RES non è quasi macchina ma una macchina
non conforme: non si può scaricare sull'acquirente o utilizzatore obblighi
normativi gravanti sul fabbricante.


## Le Quasi-Macchine

le quasi macchine possono non rispettare tutti i RES anzi, tipicamente è così!

tutto ciò che è mancante per ovvio esigenze pratiche, va descritto in modo
esplicito nel manuale d'uso e installazione della macchina

una quasi-macchina è un insieme che non è completo a funzionare così com'è

una quasi-macchina non diventa una macchina viene integrata in una macchina!

> **_attrezzatura_** è tutto quello che non è né macchine né quasi-macchina

un'oggetto privo di circuiti di comando non fa nulla! quindi non potrà mai
essere una macchina, circuiti di comando che sono preponderanti per l'attuazione
degli organi (che devono essere in movimento)

> insiemi di macchine o quasi-macchine: hanno un comportamento solidale, cioè
macchine collgeate tra loro fisicamente, e soddisfano (punto 38) tre requisiti:
	- misure di protezioni autonome
	- le unità costitutive hanno un quadro di comando comune
	- sono collegate in modo funzionale in modo da influire sul funzionamento
	delle altre ergo, serve una valutazione del rischio comune (complessiva) e
	non macchina per macchina, ma globale

se gli oggetti sono collegati assieme (ache fisicamente) ma hanno protezioni e
circuiti di comando autonomi, allora non costituiscono un insieme di macchine!!

>> si può marcare CE solo quando la macchina è completamente conforme,
altrimenti non si può (indipendeza di tutti gli aspetti da altre macchine).

l'insieme di macchine è un sottocaso della definizione di macchine!
la direttiva o RM parla esplicitamente di macchina o quasi-macchina

non ho misure di protezione che dipendono dall'interfaccia comune delle macchine
e va dichiarato esplicitamente nella dichiarazione (o nel manuale)

> _stricto sensu_ con l'IIoT si richiede la marcatura CE di tutta la linea!

ma se l'utilizzatore compra macchinari da fabbricanti diversi allora ricade su
di lui la dichiarazione di conformità dell'insieme di macchine, che comunque
può delegare

>> l'insieme di macchine è una macchina, quindi vuole la marcatura CE ergo vuole
il fascicolo tecnico, esattamente come fosse una macchina, così come il manuale
etc etc..

> lock-out tag-out è solo per interventi di manutenzione e non per interventi
sull'utilizzo della macchina legati ad esempio ad una operazione di inceppamento
di un pezzo o prodotto


## Le Macchine (già) in Servizio

non sono trattate dalla direttiva macchina ma da quelle sociali (cioè nazionali
e non comunitarie)

> se la modifica ad una macchina già in servizio cambia la destinazione d'uso o
ne modifica le prestazioni, o comunque se sono stati introdotti nuovi pericoli
o se è stato incrementato il livello di rischio.

l'attuazione delle direttive sociali non è uniforme in tutti gli stati:
stabiliscono requisiti minimi ma ogni stato può aggiungerne, ad esempio quando
lo stato italiano aggiunge che l'adeguamento della macchina deve essere fatto
allo stato dell'arte, che è un concetto sfumatissimo, visto che non è scritto,
varia nel tempo, varia da settore in settore.

>> il nuovo RM prescrive la targa del fabbricante a meno della marcatura CE
(prima non era così)

dls 81/08 ribadisce che interventi migliorativi per la sicurezza del macchinario
non implicano una rimarcatura CE del macchinario

> nel nuovo RM si aggiunge che la nuova modifica per essere sostanziale aggiunge
che è necessario aggiungere ripari o dispositvi di protezione che implichino una
modifica delle funzioni di sicurezza (vs. modifica semplice) quindi non è
necessario rimarcare CE la macchina - cioè il nuovo RM è più permissivo da
questo punto di vista.

il cambio di prestazioni ha un senso nel momento in cui queste cambino i rischi,
diversamente decadono

se aggiungo un riparo ma non modifico il sistema / circuito di comando allora
non devo rimarcare, però attenzione! quando modifico una macchina la
documentazione va sempre aggiornata e modificare la valutazione dei rischi in
cui si escplicita ciò

**_punto 39_** della guida (non è presente nella direttiva): [..] se l'aggiunta
di F modifica i rischi di E (insime di A, B, C, D), allora non devo rimarcare E
ma documentarlo in cui spiego perché e per come dovrò fare un fascilo tecnico di
come fare questo inserimento.

se l'inserimento del nuovo macchinario non influenza tutto l'insieme allora non
si deve rimarcare tutto! ma solamente il macchinario che integra la
quasi-macchina

F è quasi macchina, quindi chi la produce ti dice quali res rispetta, ed i
restanti li devo integrare e riportare io nel fasciolo tecnico.
se il fabbricante di F cura anche l'integrazione allora spetterà lui la
marcatura dell'inserimento della quasi-macchina F nell'insieme E, diversamente
spetterà all'utilizzatore - che però potrà appaltare tale funzione a un
consulente

> di fatto è fondamentale capire se la modifica è locale vs. globale

> questa dichiarazione di conformità è indicata come _**as assembled**_
> e va ri-emessa tutte le volte che cambio i rischi o introduco dei pericoli
nuovi

> la nuova marcatura non è di **_F_** (che è una quasi-macchina) ma della
incorporazione di **_F in E_**

> **dichiarazione di incorporazione** _vs._ **di conformità**


## Gli Operatori Economici

> nel momento in cui io apponga la targa con la marcatura CE io divento il
fabbricante

> in qualità di fabbricante dobbiamo essere in possesso del fasciolo tecnico,
anche nel caso in cui io realizassi macchine ad uso proprio (non immesse sul
mercato)

> _**mandatario**_: è qualcuno a cui il fabbricante ha delegato alcuni compiti,
a seconda degli accordi; si tratta di una figura non obbligatoria!

> nell'ambito dell'Unione Europea, è anche detto un **rappresentante
autorizzato**
> non può essere delegato per compiti di natura tecnica!
né può avere responsablità inerenti alla conformità della macchina
> però può firmare la dichiarazione di conformità

> questa delega non è un obbliga ma una possibilità


### Importatori

> fornitore di servizi di logistica non c'è nel nuovo RM

> le definizioni di **distributore** e **fornitore** tendono a sovrapporsi 

> distinzione se il fabbricante è EU o extra EU

> importatore soggetto responsabile è colui che lo immette sul mercato

> l'importatore è colui che immette sul mercato ma non è lui che ha l'obbligo di
marcare CE

> che mette il nome diventa il fabbricante, diversamente rimane importatore

> immisione in libera pratica vs. immissione per completamento prima dell'
immissione sul libero mercato del territorio dell'UE.

> ci possono essere più importatori per lo stesso prodotto, ognuno però è
responsabile per il solo prodotto che importa

> un prodotto può essere importato sul mercato solamente se c'è un soggetto
responsabile all'adempimento di tutti gli obblighi di legge previsti

> palesità dell'insufficienza quando si analizza il fascilo tecnico quando si fa
l'importatore, per il quale prodotto si diventa garanti della documentazione
tecnica - per il qual obbligo dovrebbe scaricare tutto al fabbricante che, ove
non adempie, grava sull'importatore

> tutte le norme di prodotto sono così, cioè hanno questo inquadramento

> il momento in cui un prodotto deve essere confermo è quello in cui viene
immesso sul mercato

> l'importatore è quindi una figura di garanzia

ogni prodotto deve essere identificato con il nome dell'importatore oltra a
quello del fabbricante, con numero di telefono e posta elettronica.

io, de facto, come importatore divento garante nel momento in cui il fabbricante
non risponde

> discorso sulle **azioni correttive**


#### Distributori (aka rivenditori)

hanno solamente obblighi di carattere formale, cioè di verifica cha sia già
tutto in ordine ed in regola

> ogni operatore economico deve garantire la rintracciabilità

> il nome dell'importatore deve essere riportatore al fianco di quello del
fabbricante



## Direttive e Regolamenti Specifici

vi sono alcune direttive che si applicano ed escludono la direttiva macchine,
come la ATEX ma solo di alcune sue parti (alcuni suoi requisiti) inevece alcune
come la direttiva ascensori, ed alimenti la escludono / sostituiscono
completamente ed altre che invece si applicano in aggiunta alla direttiva
macchine

alcune non hanno nulla a che fare con la sicurezza ma sono sul funzionamento dei
prodotti

## Sulle Norme e lo Stato dell'Arte

tre differenti tipi:
- tipo A: concetti generali
- tipo B: di sicurezza
- tpoo C: di prodotto


se v'è una norma nazionale in contrasto con quella europea, allora quella
nazionale va rimossa perché di ostacolo al commercio, e valgono quelle
comunitarie

> le norme codificano lo stato dell'arte
> sono sempre testi non obbligatorie ma se le rispetto sono sempre presunto
conforme rispetto al rispetto della conformità alla direttiva

> lo stato dell'arte è stabile nel tempo e diffuso, e devo verificarlo
analizzando cosa c'è sul mercato

> tiene conto di vincoli tecnici, economici, prestazionali, usabilità
> devo verificare cosa fa la concorrenza, quali dispositivi sono disponibili sul
mercato, consulare esperti, e conoscere la tecnica attuale

### Ancora sulle Norme e lo Stato dell'Arte

se io rispetto una norma, e questa è armonizzata, allora sono presunto conforme
> può accadere però che una norma sia superata dallo stato dell'arte ma mai il
contrario!

> ergo la norma stabilisce il minimo sindacale per essere godere della
presunzione di conformità

> a volte non si può fare ciò che chiede tecnicamente una norma, ma in questo
caso l'onore della prova di essere conformi diventa del costruttore ergo sempre
meglio aderire al rispetto di una norma tecnica quando questa esiste e se si
riesce tecnicamente (norma armonizzata)

> non c'è nessuno scarico di responsabilità possibile, quindi se qualcosa non va
tecnicamente fatto allora non bisogna farlo, e non vale nessun accordo tra le
parti di scarico responsabilità se uno è fabbricante

obiettivo è comunque quello di una normativa di prodotto, e che quindi va a
tutelare più il mercato, il suo prodotto e quindi tutela maggiornmente il
consumatore che non il fabbricante

> il RM è una norma di prodotto

> comandi manuali ad azione mantenuta sarebbe **FORBIDDEN**


### sull'allegato iv

se la macchina è contemplata dall'allegato iv ed è fabbricata conformemente alle
norme armonizzare allora si possa per una certificazione CE del tipo di cui all'
allegato iv, ovvero non si parla più di dichiarazione ma certificazione.

se la macchina non è coperta da una norma arnomizzata

nel nuovo RM l'allegato iv è diventato l'allegato i, dopodiché la francia ha
proposto la certificazione da organismi / enti accreditati
alla fine si è trovato il compromesso dividendo l'allegato i in due parti, la
prima in cui vi sono macchine che hanno bisogno di essere certificate da enti ed
altre che possono [..]

si parla di comportamento totalmente o parzialmente auto-evolutivo 

anche se norma di tipo c, ora non posso più fare da solo, se sono nella parte a
dell' allegato i.) però se sono nella parte b, allora posso fare senza l'ente
certificatore od organismo notificato - deve però esistere la norma di tipo c

esistono poi tutta una serie di clausole che consentono alla commissione europea
di intervenire durante tale processo di normazione e certificazione quindi con
conferimento di poteri ex-ante

stiamo sempre parlando di componenti di sicurezza!

componenti totalmente o parzialmente auto-evolutivo da questo punto di vista

### documentazione

come hai fatto presto a portarlo il dolcino quando te l'ha chiesto andrea

> ora può essere fornibile in formato digitale, ed eventualmente disponibile
su un sito internet per almeno 10 anni
> però entro 1 mese il consumatore ha diritto a richiederne una copia in formato
cartaceo gratuitamente

> l'indirizzo è quello di passare quanto più possibile alla fornitura digitale

> al fianco della marcatura CE è obbligatorio indicare il sito internet e
contatti di riferimento del fabbricante

> il rispetto delle norme armonizzate non va elencato per esplicito con la
direttiva ma lo sarà con nuovo RM
> con la vecchia direttiva andava certamente indicato nel fascilo tecnico, e si
poteva non rispettarli tutti, giustificandoli tecnicamente

> la marcatura CE la faccio come ultima cosa

> ci sono due obblighi nuovi nel rilasciare il documento ufficiale per la
**dichiarazione di conformità UE**:
- indicazione delle direttive rispettive più le norme tecniche 
- poi specificare gli estremi di pubblicazione

> non c'è più la figura che deve redigere il fascicolo tecnico -> elemento che
va nella direzione del nuovo quadro normativo

> si può citare le specifiche tecniche alle quali si è conformi ISO/IEN ma non
sono normative (cioè leggi, al max sono norme)

> però le si può citare elencandole nella dichiarazione di conformità UE, è una
possibilità non è un obbligo

> dichiarazione di incorporazione :: vedi slides

>> non c'è più il requisito che le istruzioni vadano anche nella lingua di
installazione dello stato membro ma in una lingua sancita come compatibile dallo
stato membro
> ciò mi costringe a studiare cosa prevedono le leggi dello stato membro

> questo non vale per le quasi macchine per le quali può vigere un accordo tra
le parti

con il nuovo RM inevece la lingua deve essere di facile comprensione per lo
stato memebro in cui verrà messa in servizio, e questo vale anche per le quasi
macchine indistintamente.

> la questione della lingua originale non c'è più, quindi io mi prendo la
responsabilità per la lingua che io sto fornendo, quindi questo è sostanziale
per il fabbricante
> probabilmente interverranno gli stati membri per sancire quando una lingua è
di facile comprensione


nel nuovo RM si fa esplicito riferimento di cosa devono contenere le
**istruzioni per l'assemblaggio**!
oggi, come contenuti, queste istruzioni non esistono


> nell'analisi dei valutazione dei rischi sono state aggiunti due temi:
- prevedere eventuali evoluzioni funazionali della maccchina
- determinare i rischi derivanti dall'interfaccia, ovvero da eventuali
interazioni con altri gruppi od unità

devo inoltre prevedere il test periodico (per monitoraggio) dei dispositivi di
sicurezza, o meglio fornire procedure di prova per la verifica della corretta
funzionalità e della sicurezza delle diverse unità

devo dare la possibiltà all'utente di provarle e testarle (è un requisito) e
devo fornire le procedure di come testare queste funzionalità di sicurezza

ad esempio come testo la area di lavoro safe di un robot??

sull'ergonomia!!!

.. e sul self-evolving!

c'è un res nuovo, sulla protezione contro la corruzione

tutto il discorso sulla cybersecurity non ci interesse poiché non fa parte della
direttiva macchine, nel senso che ci interessa solamente che in caso di attacco
la macchina non si comporti in modo pericolo

poi, il discorso, sulla protezione non ci interessa se non intacca questo
aspetto!

infatti gli attacchi possono essere tanto da remoto quanto locali!

il sistema deve essere adeguatamente protetto contro attacchi tanto accidentali
quanto intenzionali
la macchina deve raccogliere evidenze, poiché io devo essere in grado di
ricostruire cosa è successo

bisogna fare una valutazione del rischio di attacco informatico: oggi esistono
due rapporto tecnici: iso/tr 62463 iec/tr xx
su questi rapporti tecnici è sicuro che verranno scritte norme

sicurezza informatica generale abc 443 (per progettare le reti in modo sicuro) e
non si applicano alla macchina

il problmea della sicurezza informatica è cambia nel tempo - e molto velocemente
- come ad esempio il discorso degli antivirus

> sarà necessario istruire l'operatore come adottare misure di mitigazione del
rischio, che consentiranno di mantenere un livello di SECURITY (=! SAFETY)
adeguato

> aspetto di raccogliere le evidenze è importante!!!

> il SW deve essere identificabile in qualsiasi momento (CRC?) e facilmente
accessibile, controllarlo e verificarlo

> protezione contro la corruzione

> è stato cambiato anche il res 1.2.1: i sistemi di comando devono resistere ai
tentavi interni esterni di compromissione, accidentali e malevoli.

> nella valutazione dei rischi devo individuare un perimetro all'interno del
quale la macchina può muoversi per il suo comportamento evolutivo, oltre al
quale non potrà andare >> tutti i limite che non si potranno superare saranno
oggetto della valutazione dei rischi

> devo conservare i log SW (scatola nera) di tutte le decisioni prese per un
anno, deve cioè essere possibile riavvolgere il nastro per cercare di
ricostruire eventuali situazioni ed analizzare cosa è stato deciso dalla
macchina.

> deve sempre essere possibile correggere la macchina, ovvero poter prevalere
sulle eventuali decisioni prese dalla macchina


res 1.3.7 : funzionamento collaborativo

> si è aggiunto lo stress psicologico

documentazione tecnica ex fasciolo tecnico

>> era l'allegato vii è diventato allegato iv

il fascicolo tecnico deve contenere la logica del circuito di sicurezza,
tecnicamente già adesso dovrebbe essere così!

il 19/4 è in approvazione, dopodiché - al termine della votazione- ci sarà la
rilettura poi la pubblicazione sulla gazzetta ufficiale europea verso maggio /
giugno dopodiché il regolamento entrerà in vigore 20 giorni dopo la sua
pubblicazione e la sua applicazione dovrà avvenire entro 42 mesi tranne che per
alcuni articoli che verranno applicati prima, servono infatti per poter
applicare le norme armonizzate affinché gli organismi normanti possano
intervenire prima.

> il regolamento verrà applicato al termine dei 42 mesi: è in vigore ma non
verrà applicato!
prima non si può, continuerà a vigera la vecchia direttiva 2006/42/CE!
> quindi, indicativamente, salvo imprevisti, entrerà in vigore a **Gennaio
2027**

questi 3 anni e mezzo servono affinché i fabbricanti si adeguino e gli enti
normanti pubblichini le norme tecniche necessarie

> cominciare prima con la valutazione del rischio informatico!


la direttiva macchina è un direttiva di prodotto ma esistono direttive
contenitore (direttiva sicurezza norme di prodottto [?]) che coprono tutti quei
prodotti che non sono coperti da norme di prodotto specifiche - come ad esempio
la direttiva macchine



---
---
---
.
